name: Deploy Shindig 2 RSVP to Azure App Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Angular application
      run: npm run build -- --configuration=production

    - name: Azure Login with OIDC
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # - name: Deploy Infrastructure
    #   run: |
    #     # Create resource group if it doesn't exist
    #     az group create --name shindig --location westus3
        
    #     # Deploy App Service infrastructure with unique deployment name
    #     DEPLOYMENT_NAME="shindig-deployment-$(date +%Y%m%d%H%M%S)"
        
    #     az deployment group create \
    #       --resource-group shindig \
    #       --template-file infra/main.bicep \
    #       --parameters @infra/main.parameters.json \
    #       --name $DEPLOYMENT_NAME
        
    #     # Wait for deployment to complete
    #     az deployment group wait \
    #       --resource-group shindig \
    #       --name $DEPLOYMENT_NAME \
    #       --created

    - name: Get App Service Name
      id: get-app-name
      run: |
        APP_NAME=shindig2-rsvp
      # $(az deployment group show \
      #   --resource-group shindig-rg \
      #   --name shindig
      #   --query "[?contains(name, 'shindig-deployment')].properties.outputs.webAppName.value | [0]" \
      #   --output tsv)
      # echo "app-name=$APP_NAME" >> $GITHUB_OUTPUT

    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ steps.get-app-name.outputs.app-name }}
        slot-name: 'production'
        package: './dist/shindig-rsvp'

    - name: Configure App Service Settings
      run: |
        # Get the app name from deployment output
        APP_NAME=shindig2-rsvp
        
        # Configure environment variables
        az webapp config appsettings set \
          --resource-group shindig-rg \
          --name $APP_NAME \
          --settings \
            NODE_ENV=production \
            WEBSITE_NODE_DEFAULT_VERSION=~22 \
            AZURE_STORAGE_ACCOUNT_NAME="${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
            AZURE_STORAGE_SAS_TOKEN="${{ secrets.AZURE_STORAGE_SAS_TOKEN }}" \
            AZURE_STORAGE_TABLE_NAME="rsvpresponses" \
            AZURE_STORAGE_COMMENT_TABLE_NAME="comments"
